### ISSUE TITLE
[feat] CQLSH query performance

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench#231]
This seems to depend which OS you are running on, but running a query that returns only 100 rows (a tiny result set!) can take a very long time to be displayed.
On my system I ran the query `SELECT * FROM keyspace1.standard1 LIMIT 100;` from various OSes and this is how long it took to display the results on screen:
Linux: 7 seconds
macOS: 17 seconds
Windows 10: 60-70 seconds
Windows 11: 100 seconds

This query takes 0.09 seconds to execute in cqlsh so I would not expect it to take over 1 second to render the results on screen.

On Windows the whole UI freezes until the results are displayed

There is no user feedback to suggest that anything is happening while waiting for the query to execute, it just looks like nothing happened when you pressed Enter to submit the query.

**Comment by mhmdkrmabd** [comment]
@rgooding is this happening with a particular table or tables with many fields? Did you execute any statement before that one - like paging or expand -? Sharing more info is appreciated - This query's performance is the same way on all OSes -
![Image](https://github.com/user-attachments/assets/9c691c3c-ab11-453b-866b-94c00551545d)
