### ISSUE TITLE
[feat] Excessive CPU use when idle

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench#238]
This mainly seems to affect macOS and Linux but the CPU use while idle on Windows is a bit high too.

On each of these platforms I have launched the application, connected to a cluster and run a query or two then closed the CQLSH view, then measured the CPU use while the application is idle on the Workspace view:

Windows 10: 15-20%
Windows 11: 7-10% but Windows 11 puts the process into efficiency mode to limit its resource use
Linux: 30-60%
macOS: 30-60%

Given that the application is not doing anything I would not expect it to be using over half a CPU core and affecting the performance of other applications.

**Comment by mhmdkrmabd** [comment]
Working on that.

**Comment by mhmdkrmabd** [comment]
The main cause of the high CPU usage has been spotted and handled, I'll wait for the feedback regard the implemented changes after the next build
