### ISSUE TITLE
[feat] When deleting a workspace, give users the option to delete it from the file system also

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench#247]
Currently, when we delete a workspace we leave it on the file system.

Give users the option to delete the workspace from the filesystem

**Comment by digiserg** [comment]
I think it shouldn't be optional. If you delete it means both config and filesystem to me.

**Comment by millerjp** [comment]
@digiserg no - we can have a workspace thats in Git containing cluster details. If and individual user deletes this and checks in/updates etc.. they may not want it reflected in source control. It definitely needs to be optional and we should have the same behaviour on other things like this.
