### ISSUE TITLE
[feat]: Add grouping in tree for system keyspaces, similar to virtual keyspaces

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench#375]
We should add a new grouping "System Keyspaces" on the tree and group the system keyspaces under this (as in virtual keyspaces).

<img width="234" alt="Screenshot 2024-09-09 at 16 55 10" src="https://github.com/user-attachments/assets/1f2159af-7da7-4252-9229-383c5c0fa2c2">

These are the system keyspaces to add here:

- system
- system_schema
- system_auth
- system_traces
- system_distributed

Also, order all the keyspaces alphabetically ascending so the order is predictable see #387 and #391 in all the groups

**Comment by mhmdkrmabd** [comment]
Working on that
