### ISSUE TITLE
[bug]: New keyspaces are not displayed

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench#397]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240911-01

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Linux

### Operating System Version

Debian 12

### Apache Cassandra Version(s)

4.0.13 (also reproduced with 5.0)

### Bug Description

New keyspaces are not being displayed in the Keyspaces list. It refreshes when a new keyspace is added but the new keyspace is not displayed, also refreshing manually does not make the new keyspace appear in the list.

### Steps to Reproduce

Create a new keyspace while you have the cluster open in Workbench. Look at the list of keyspaces displayed in the left-hand panel, the new keyspace is not there.

### Expected Behavior

New keyspaces should be displayed immediately after creation

### Actual Behavior

New keyspaces are not displayed.

### Severity

Medium

### Further Information

Please see this video of the issue:
https://github.com/user-attachments/assets/4c526d94-58e7-4753-8f4d-1c87eb690bf8

**Comment by mhmdkrmabd** [comment]
Changes implemented in the binaries repo related to this issue - `for-issue-397` branch -

**Comment by digiserg** [comment]
Tested. It works now.
