### ISSUE TITLE
[bug]: Disable displaying replication settings on virtual keyspaces as it does not exist for them

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench#406]
<img width="317" alt="Screenshot 2024-09-12 at 08 49 01" src="https://github.com/user-attachments/assets/726765b3-97f1-4960-ae13-b212c7eae242">

**Comment by HadesArchitect** [comment]
I believe this one is done in 0.9.1

<img width="295" alt="image" src="https://github.com/user-attachments/assets/4fa9ef9a-4bb6-47ab-b0aa-247d32bbb64f">
