### ISSUE TITLE
[bug]: update notifier broke after adding `v` to the tags

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench#462]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

1.0.0-beta2

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Apache Cassandra Version(s)

4.1.5

### Bug Description

<img width="530" alt="image" src="https://github.com/user-attachments/assets/9d0c323a-7d4c-4922-ad0c-ffb3455aa607">

### Steps to Reproduce

Just open it up

### Expected Behavior

no update required

### Actual Behavior

it's asking me to update

### Severity

High

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by digiserg** [comment]
Its still broken on the latest release

**Comment by millerjp** [comment]
@digiserg @mhmdkrmabd is this fixed now?

**Comment by mhmdkrmabd** [comment]
Yes it should be fixed, I'll close it.
