### ISSUE TITLE
[bug]:  Indicate when no results are returned

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench#471]
Indicate when no results are found rather than just saying executed statment - say "CQL statement executed - no data found"

<img width="723" alt="Screenshot 2024-09-30 at 18 23 11" src="https://github.com/user-attachments/assets/92af7500-4be7-41e1-855f-56079b0d62e7">

**Comment by mhmdkrmabd** [comment]
@millerjp 
![Image](https://github.com/user-attachments/assets/ddfd1c96-0fe1-4bf3-8aed-a067c011adc9)
