### ISSUE TITLE
[feat]: Upgrade monaco-editor from 0.46.0 to 0.51.0 (or latest)

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench#485]
See the snyk PR generated - this upgrade breaks something and needs to be fixed post 1.0

https://github.com/axonops/axonops-workbench/pull/483

**Comment by mhmdkrmabd** [comment]
@millerjp  we shouldn't do that for now, this upgrade has caused all rendered editors to be fully broken, and after many tests, the error is mostly about compatibility issues with Electron, so I recommend sticking with the latest stable version we've found.

We already have upgraded from `v0.34.1` to `v0.46.0`, we'll keep an eye on the upcoming versions and upgrade when it's compatible.

**Comment by millerjp** [comment]
@mhmdkrmabd we will need to have a look at this in 1.1 and assess it there
