### ISSUE TITLE
[bug]: Empty line after CQL attempts to be executed

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench#527]
I pasted this into the enhance console

```
CREATE KEYSPACE example WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': '1'} AND durable_writes = true;

```

<img width="1368" alt="Screenshot 2024-10-29 at 14 52 21" src="https://github.com/user-attachments/assets/ab62a2fb-c997-4cfc-85e9-6b0161d939ed">

I think its picking up the empty line and trying to run it

**Comment by mhmdkrmabd** [comment]
Working on that
