### ISSUE TITLE
[bug]: Release 0.9.2 not launchable on MacOS

### ISSUE THREAD

**Issue by gk-fschubert** [axonops/axonops-workbench#618]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent release

### AxonOps Workbench Version

0.9.2

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

15.1.1 on a M1

### Bug Description

I'm not able to start the application: 

```bash
$_> open -n /Applications/AxonOps\ Workbench.app                                                                                                                                                           
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600003a283f0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

### Steps to Reproduce

Download, install and try to start. 

### Expected Behavior

It starts

### Actual Behavior

it does not start

### Severity

High

**Comment by digiserg** [comment]
Thank you for the report. I'm looking into it now.

**Comment by digiserg** [comment]
It looks like my recent build changes to support the Apple Store are to blame. I rebuild the app and it works now.

Thank you again for your quick bug report.

https://github.com/axonops/axonops-workbench/releases/tag/v0.9.2
