### ISSUE TITLE
[feat]: Unlock Github Discussions

### ISSUE THREAD

**Issue by HadesArchitect** [axonops/axonops-workbench#623]
**Is your feature request related to a problem? Please describe.**
Only project team members are allowed to create new discussions. Non-team members can't create a new discussion, only comment on an existing one. It's recommended to use Github Discussions to offer and discuss new feature ideas, but I can't do it :) 

**Describe the solution you'd like**
Unlock Github Discussions to allow any authorised github user to write there.

**Describe alternatives you've considered**
none

**Additional context**
Notice missing "New Discussion" button
<img width="692" alt="image" src="https://github.com/user-attachments/assets/b08203a4-8908-4e65-aecb-42be0fe9f4b7" />

**Comment by millerjp** [comment]
@HadesArchitect I have had a look and cant figure out how to do this. We hadnt locked them down like this. I will continue to see if this is possible

**Comment by millerjp** [comment]
@HadesArchitect I have added your account to the repo - you should be able to create discussions now. I will try and figure out how to make this available to everyone, although I am not sure github lets you do that

**Comment by HadesArchitect** [comment]
Thanks Johnny!

**Comment by HadesArchitect** [comment]
Sorry to disappoint you but I still can't write there 😅

**Comment by HadesArchitect** [comment]
This should help: https://docs.github.com/en/organizations/managing-organization-settings/managing-discussion-creation-for-repositories-in-your-organization#allowing-or-disallowing-users-with-read-access-to-create-discussions

**Comment by millerjp** [comment]
@HadesArchitect I think I found it in the org settings. I have removed your account from the project now. Can you test you can still create discussions?

**Comment by HadesArchitect** [comment]
LGTM

ср, 11 дек. 2024 г., 17:20 Johnny Miller ***@***.***>:
