### ISSUE TITLE
[feat]: Developer Experience - Onboarding documentation is incomplete

### ISSUE THREAD

**Issue by HadesArchitect** [axonops/axonops-workbench#629]
**Is your feature request related to a problem? Please describe.**
At the moment, development documentation only describes `npm install` step, which is not enough to have the Workbench fully operational. After launch, it complains about the lack of binaries.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/0b91e65d-fbbd-4c56-b043-3d334d4e28f3" />

**Describe the solution you'd like**
Developer documentation has to be extended. **I'll be glad to do a pull request, but I need some hints first :)** 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mhmdkrmabd** [comment]
Hey @HadesArchitect, thanks for raising the ticket! Indeed we should add a part about the binaries dependencies, users can install a ready-to-use exectuable versions of the binaries from the official repo:
https://github.com/axonops/axonops-workbench-cqlsh/releases/latest

Or, for sure, they can clone the project and build the binaries by their own, binaries should be in the `main/bin` folder directory with specific names, they can one file or a directory
![image](https://github.com/user-attachments/assets/44e25c74-ae9b-4745-9820-b3858a73267a) 

We'll add this section in the upcoming PRs, but feel fry to create a PR and we'll adjust if needed to, approve and merge.

**Comment by HadesArchitect** [comment]
Many thanks @mhmdkrmabd
