### ISSUE TITLE
[feat] Create chocolatey installer for Windows

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench#63]
https://chocolatey.org/

**Comment by DigitalMarc** [comment]
[chocolateyCassandra3_7.zip](https://github.com/user-attachments/files/16174536/chocolateyCassandra3_7.zip)

In the attached zip you'll find what has been done back in the days for cassandra 3.7:
nuspec file with a ps1 script

**Comment by digiserg** [comment]
> [chocolateyCassandra3_7.zip](https://github.com/user-attachments/files/16174536/chocolateyCassandra3_7.zip)
> 
> In the attached zip you'll find what has been done back in the days for cassandra 3.7: nuspec file with a ps1 script

Thanks @DigitalMarc

**Comment by digiserg** [comment]
The github pipeline is ready and working. We just need a corporate account to push the package @hshimizu

**Comment by millerjp** [comment]
@digiserg have sent you the chocolatey details to use
